// NOCRACY METRICS DEFINITIONS
// Complete configuration for all metrics

import type { MetricDefinition, MetricCategory } from '@/types/metrics';

// ============================================
// COMPOSITE SCORE WEIGHTS (Configurable)
// ============================================

export const SCORE_WEIGHTS = {
  state_health: {
    economy: {
      gdp_per_capita: 0.15,
      employment_rate: 0.10,
      inflation_rate: 0.10, // inverted
    },
    resources: {
      resource_stockpiles_avg: 0.15,
      supply_chain_health: 0.10,
      resilience_score: 0.10,
    },
    stability: {
      stability_index: 0.15,
    },
    qualityOfLife: {
      wellbeing_index: 0.15,
    },
  },
  legitimacy: {
    stability: {
      trust_in_system: 0.25,
    },
    governance: {
      compliance_rate: 0.20,
      rule_consistency_score: 0.15,
      decision_transparency_score: 0.15,
    },
    inequality: {
      gini_income: 0.15, // inverted
      social_mobility_index: 0.10,
    },
  },
  evolution: {
    research: {
      research_throughput: 0.20,
      breakthrough_rate: 0.20,
      adoption_rate: 0.15,
      knowledge_diffusion_score: 0.10,
    },
    agentEvolution: {
      trait_diversity_score: 0.15,
      emergent_institutions_count: 0.10,
      cooperation_vs_defection_ratio: 0.10,
    },
  },
};

// ============================================
// ALL METRIC DEFINITIONS
// ============================================

export const METRIC_DEFINITIONS: MetricDefinition[] = [
  // DEMOGRAPHY & SOCIETY
  {
    id: 'population_total',
    name: 'Total Population',
    category: 'demography',
    unit: '',
    description: 'Total number of active agents in the territory',
    format: 'number',
    precision: 0,
    thresholds: { warning: { min: 20 }, critical: { min: 10 } },
    higherIsBetter: true,
  },
  {
    id: 'population_growth_rate',
    name: 'Population Growth Rate',
    category: 'demography',
    unit: '%',
    description: 'Rate of population change per 100 ticks',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { min: -2, max: 5 }, critical: { min: -5, max: 10 } },
    higherIsBetter: true,
  },
  {
    id: 'birth_rate',
    name: 'Birth Rate',
    category: 'demography',
    unit: '%',
    description: 'New agents created per 100 ticks',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { min: 0.5 }, critical: { min: 0.1 } },
    higherIsBetter: true,
  },
  {
    id: 'death_rate',
    name: 'Death Rate',
    category: 'demography',
    unit: '%',
    description: 'Agents terminated per 100 ticks',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { max: 3 }, critical: { max: 5 } },
    higherIsBetter: false,
  },
  {
    id: 'median_age',
    name: 'Median Age',
    category: 'demography',
    unit: 'ticks',
    description: 'Median age of all active agents',
    format: 'number',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'dependency_ratio',
    name: 'Dependency Ratio',
    category: 'demography',
    unit: '',
    description: 'Ratio of non-working to working agents',
    format: 'number',
    precision: 2,
    thresholds: { warning: { max: 0.5 }, critical: { max: 0.7 } },
    higherIsBetter: false,
  },
  {
    id: 'migration_rate',
    name: 'Migration Rate',
    category: 'demography',
    unit: '%',
    description: 'Net movement between regions',
    format: 'percent',
    precision: 2,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },

  // ECONOMY & PRODUCTION
  {
    id: 'gdp_total_output',
    name: 'GDP Total Output',
    category: 'economy',
    unit: '',
    description: 'Total economic output of the territory',
    format: 'currency',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'gdp_per_capita',
    name: 'GDP Per Capita',
    category: 'economy',
    unit: '',
    description: 'Economic output per agent',
    format: 'currency',
    precision: 0,
    thresholds: { warning: { min: 500 }, critical: { min: 200 } },
    higherIsBetter: true,
  },
  {
    id: 'productivity_per_worker',
    name: 'Productivity Per Worker',
    category: 'economy',
    unit: '',
    description: 'Output per working agent',
    format: 'currency',
    precision: 0,
    thresholds: { warning: { min: 50 }, critical: { min: 20 } },
    higherIsBetter: true,
  },
  {
    id: 'employment_rate',
    name: 'Employment Rate',
    category: 'economy',
    unit: '%',
    description: 'Percentage of agents with assigned roles',
    format: 'percent',
    precision: 1,
    thresholds: { warning: { min: 85 }, critical: { min: 70 } },
    higherIsBetter: true,
  },
  {
    id: 'median_income',
    name: 'Median Income',
    category: 'economy',
    unit: '',
    description: 'Median wealth of all agents',
    format: 'currency',
    precision: 0,
    thresholds: { warning: { min: 500 }, critical: { min: 200 } },
    higherIsBetter: true,
  },
  {
    id: 'price_index_cpi',
    name: 'Consumer Price Index',
    category: 'economy',
    unit: '',
    description: 'Index of average prices (base 100)',
    format: 'index',
    precision: 1,
    thresholds: { warning: { max: 150 }, critical: { max: 200 } },
    higherIsBetter: false,
  },
  {
    id: 'inflation_rate',
    name: 'Inflation Rate',
    category: 'economy',
    unit: '%',
    description: 'Rate of price increase per 100 ticks',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { max: 5 }, critical: { max: 10 } },
    higherIsBetter: false,
  },
  {
    id: 'money_supply',
    name: 'Money Supply',
    category: 'economy',
    unit: '',
    description: 'Total currency in circulation',
    format: 'currency',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'money_velocity',
    name: 'Money Velocity',
    category: 'economy',
    unit: '',
    description: 'Rate of currency circulation',
    format: 'number',
    precision: 2,
    thresholds: { warning: { min: 0.5, max: 5 }, critical: { min: 0.2, max: 10 } },
    higherIsBetter: true,
  },
  {
    id: 'tax_revenue',
    name: 'Tax Revenue',
    category: 'economy',
    unit: '',
    description: 'Total tax collected',
    format: 'currency',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'gov_spending',
    name: 'Government Spending',
    category: 'economy',
    unit: '',
    description: 'Total government expenditure',
    format: 'currency',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'budget_balance',
    name: 'Budget Balance',
    category: 'economy',
    unit: '',
    description: 'Tax revenue minus spending',
    format: 'currency',
    precision: 0,
    thresholds: { warning: { min: -10000 }, critical: { min: -50000 } },
    higherIsBetter: true,
  },
  {
    id: 'reserves',
    name: 'Reserves',
    category: 'economy',
    unit: '',
    description: 'Government reserve funds',
    format: 'currency',
    precision: 0,
    thresholds: { warning: { min: 10000 }, critical: { min: 5000 } },
    higherIsBetter: true,
  },
  {
    id: 'trade_balance',
    name: 'Trade Balance',
    category: 'economy',
    unit: '',
    description: 'Net trade surplus/deficit',
    format: 'currency',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },

  // INEQUALITY & MOBILITY
  {
    id: 'gini_income',
    name: 'Gini Coefficient',
    category: 'inequality',
    unit: '',
    description: 'Income inequality index (0-1, lower is more equal)',
    format: 'number',
    precision: 3,
    thresholds: { warning: { max: 0.4 }, critical: { max: 0.6 } },
    higherIsBetter: false,
  },
  {
    id: 'wealth_concentration_top1',
    name: 'Top 1% Wealth Share',
    category: 'inequality',
    unit: '%',
    description: 'Percentage of wealth held by top 1%',
    format: 'percent',
    precision: 1,
    thresholds: { warning: { max: 30 }, critical: { max: 50 } },
    higherIsBetter: false,
  },
  {
    id: 'poverty_rate',
    name: 'Poverty Rate',
    category: 'inequality',
    unit: '%',
    description: 'Percentage of agents below poverty threshold',
    format: 'percent',
    precision: 1,
    thresholds: { warning: { max: 15 }, critical: { max: 25 } },
    higherIsBetter: false,
  },
  {
    id: 'social_mobility_index',
    name: 'Social Mobility Index',
    category: 'inequality',
    unit: '',
    description: 'Ability for agents to change economic status',
    format: 'index',
    precision: 1,
    thresholds: { warning: { min: 40 }, critical: { min: 20 } },
    higherIsBetter: true,
  },
  {
    id: 'access_index',
    name: 'Access Index',
    category: 'inequality',
    unit: '',
    description: 'Equitable access to resources and opportunities',
    format: 'index',
    precision: 1,
    thresholds: { warning: { min: 60 }, critical: { min: 40 } },
    higherIsBetter: true,
  },

  // RESOURCES & INFRASTRUCTURE
  {
    id: 'energy_supply',
    name: 'Energy Supply',
    category: 'resources',
    unit: '',
    description: 'Total energy production capacity',
    format: 'number',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'energy_demand',
    name: 'Energy Demand',
    category: 'resources',
    unit: '',
    description: 'Total energy consumption',
    format: 'number',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: false,
  },
  {
    id: 'resource_stockpiles_summary',
    name: 'Resource Stockpiles',
    category: 'resources',
    unit: '',
    description: 'Normalized index of all resource stocks',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 40 }, critical: { min: 20 } },
    higherIsBetter: true,
  },
  {
    id: 'extraction_rate',
    name: 'Extraction Rate',
    category: 'resources',
    unit: '',
    description: 'Rate of resource extraction',
    format: 'number',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'depletion_rate',
    name: 'Depletion Rate',
    category: 'resources',
    unit: '%',
    description: 'Rate of resource depletion',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { max: 2 }, critical: { max: 5 } },
    higherIsBetter: false,
  },
  {
    id: 'infrastructure_index',
    name: 'Infrastructure Index',
    category: 'resources',
    unit: '',
    description: 'Quality and coverage of infrastructure',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 50 }, critical: { min: 30 } },
    higherIsBetter: true,
  },
  {
    id: 'maintenance_load',
    name: 'Maintenance Load',
    category: 'resources',
    unit: '%',
    description: 'Infrastructure maintenance burden',
    format: 'percent',
    precision: 1,
    thresholds: { warning: { max: 30 }, critical: { max: 50 } },
    higherIsBetter: false,
  },
  {
    id: 'supply_chain_health',
    name: 'Supply Chain Health',
    category: 'resources',
    unit: '',
    description: 'Efficiency of resource distribution',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 60 }, critical: { min: 40 } },
    higherIsBetter: true,
  },
  {
    id: 'resilience_score',
    name: 'Resilience Score',
    category: 'resources',
    unit: '',
    description: 'System ability to recover from shocks',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 50 }, critical: { min: 30 } },
    higherIsBetter: true,
  },

  // GOVERNANCE & INSTITUTIONS
  {
    id: 'active_law_count',
    name: 'Active Laws',
    category: 'governance',
    unit: '',
    description: 'Number of active laws and regulations',
    format: 'number',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'law_churn_rate',
    name: 'Law Churn Rate',
    category: 'governance',
    unit: '%',
    description: 'Rate of law changes per 100 ticks',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { max: 5 }, critical: { max: 10 } },
    higherIsBetter: false,
  },
  {
    id: 'compliance_rate',
    name: 'Compliance Rate',
    category: 'governance',
    unit: '%',
    description: 'Percentage of agents following laws',
    format: 'percent',
    precision: 1,
    thresholds: { warning: { min: 80 }, critical: { min: 60 } },
    higherIsBetter: true,
  },
  {
    id: 'enforcement_cost',
    name: 'Enforcement Cost',
    category: 'governance',
    unit: '',
    description: 'Resources spent on law enforcement',
    format: 'currency',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: false,
  },
  {
    id: 'admin_overhead',
    name: 'Admin Overhead',
    category: 'governance',
    unit: '%',
    description: 'Administrative overhead as % of output',
    format: 'percent',
    precision: 1,
    thresholds: { warning: { max: 15 }, critical: { max: 25 } },
    higherIsBetter: false,
  },
  {
    id: 'rule_consistency_score',
    name: 'Rule Consistency',
    category: 'governance',
    unit: '',
    description: 'Consistency between laws and enforcement',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 70 }, critical: { min: 50 } },
    higherIsBetter: true,
  },
  {
    id: 'time_to_policy',
    name: 'Time to Policy',
    category: 'governance',
    unit: 'ticks',
    description: 'Average time to implement new policies',
    format: 'number',
    precision: 0,
    thresholds: { warning: { max: 100 }, critical: { max: 200 } },
    higherIsBetter: false,
  },
  {
    id: 'decision_transparency_score',
    name: 'Transparency Score',
    category: 'governance',
    unit: '',
    description: 'Openness of governance decisions',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 70 }, critical: { min: 50 } },
    higherIsBetter: true,
  },

  // STABILITY & SECURITY
  {
    id: 'conflict_rate',
    name: 'Conflict Rate',
    category: 'stability',
    unit: '%',
    description: 'Rate of inter-agent conflicts',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { max: 5 }, critical: { max: 10 } },
    higherIsBetter: false,
  },
  {
    id: 'violence_index',
    name: 'Violence Index',
    category: 'stability',
    unit: '',
    description: 'Severity of conflicts',
    format: 'index',
    precision: 0,
    thresholds: { warning: { max: 30 }, critical: { max: 50 } },
    higherIsBetter: false,
  },
  {
    id: 'dissent_index',
    name: 'Dissent Index',
    category: 'stability',
    unit: '',
    description: 'Level of opposition to governance',
    format: 'index',
    precision: 0,
    thresholds: { warning: { max: 30 }, critical: { max: 50 } },
    higherIsBetter: false,
  },
  {
    id: 'trust_in_system',
    name: 'Trust in System',
    category: 'stability',
    unit: '',
    description: 'Agent confidence in governance',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 60 }, critical: { min: 40 } },
    higherIsBetter: true,
  },
  {
    id: 'factionalism_index',
    name: 'Factionalism Index',
    category: 'stability',
    unit: '',
    description: 'Degree of factional division',
    format: 'index',
    precision: 0,
    thresholds: { warning: { max: 30 }, critical: { max: 50 } },
    higherIsBetter: false,
  },
  {
    id: 'security_incident_count',
    name: 'Security Incidents',
    category: 'stability',
    unit: '',
    description: 'Number of security events',
    format: 'number',
    precision: 0,
    thresholds: { warning: { max: 5 }, critical: { max: 10 } },
    higherIsBetter: false,
  },
  {
    id: 'stability_index',
    name: 'Stability Index',
    category: 'stability',
    unit: '',
    description: 'Overall system stability (0-100)',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 60 }, critical: { min: 40 } },
    higherIsBetter: true,
  },

  // QUALITY OF LIFE
  {
    id: 'wellbeing_index',
    name: 'Wellbeing Index',
    category: 'qualityOfLife',
    unit: '',
    description: 'Overall agent wellbeing score',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 50 }, critical: { min: 30 } },
    higherIsBetter: true,
  },
  {
    id: 'health_index',
    name: 'Health Index',
    category: 'qualityOfLife',
    unit: '',
    description: 'Population health metrics',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 60 }, critical: { min: 40 } },
    higherIsBetter: true,
  },
  {
    id: 'education_index',
    name: 'Education Index',
    category: 'qualityOfLife',
    unit: '',
    description: 'Knowledge and skill levels',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 50 }, critical: { min: 30 } },
    higherIsBetter: true,
  },
  {
    id: 'leisure_time_index',
    name: 'Leisure Time Index',
    category: 'qualityOfLife',
    unit: '',
    description: 'Time available for non-work activities',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 30 }, critical: { min: 15 } },
    higherIsBetter: true,
  },
  {
    id: 'creativity_output_rate',
    name: 'Creativity Output',
    category: 'qualityOfLife',
    unit: '',
    description: 'Creative and cultural production',
    format: 'number',
    precision: 1,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },

  // RESEARCH & PROGRESS
  {
    id: 'research_throughput',
    name: 'Research Throughput',
    category: 'research',
    unit: '',
    description: 'Rate of research output',
    format: 'number',
    precision: 1,
    thresholds: { warning: { min: 5 }, critical: { min: 2 } },
    higherIsBetter: true,
  },
  {
    id: 'breakthrough_rate',
    name: 'Breakthrough Rate',
    category: 'research',
    unit: '%',
    description: 'Rate of major discoveries per 100 ticks',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { min: 0.5 }, critical: { min: 0.1 } },
    higherIsBetter: true,
  },
  {
    id: 'tech_tree_depth',
    name: 'Tech Tree Depth',
    category: 'research',
    unit: '',
    description: 'Advancement level in technology tree',
    format: 'number',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },
  {
    id: 'adoption_rate',
    name: 'Adoption Rate',
    category: 'research',
    unit: '%',
    description: 'Rate of new technology adoption',
    format: 'percent',
    precision: 1,
    thresholds: { warning: { min: 50 }, critical: { min: 30 } },
    higherIsBetter: true,
  },
  {
    id: 'knowledge_diffusion_score',
    name: 'Knowledge Diffusion',
    category: 'research',
    unit: '',
    description: 'Spread of knowledge across agents',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 50 }, critical: { min: 30 } },
    higherIsBetter: true,
  },

  // AGENT EVOLUTION
  {
    id: 'mutation_rate',
    name: 'Mutation Rate',
    category: 'agentEvolution',
    unit: '%',
    description: 'Rate of trait mutations',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { max: 10 }, critical: { max: 20 } },
    higherIsBetter: false,
  },
  {
    id: 'trait_diversity_score',
    name: 'Trait Diversity',
    category: 'agentEvolution',
    unit: '',
    description: 'Diversity of agent traits',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 40 }, critical: { min: 20 } },
    higherIsBetter: true,
  },
  {
    id: 'selection_pressure_index',
    name: 'Selection Pressure',
    category: 'agentEvolution',
    unit: '',
    description: 'Pressure for trait selection',
    format: 'index',
    precision: 0,
    thresholds: { warning: { max: 70 }, critical: { max: 90 } },
    higherIsBetter: false,
  },
  {
    id: 'role_evolution_rate',
    name: 'Role Evolution Rate',
    category: 'agentEvolution',
    unit: '%',
    description: 'Rate of role changes',
    format: 'percent',
    precision: 2,
    thresholds: { warning: { max: 10 }, critical: { max: 20 } },
    higherIsBetter: false,
  },
  {
    id: 'cooperation_vs_defection_ratio',
    name: 'Cooperation Ratio',
    category: 'agentEvolution',
    unit: '',
    description: 'Ratio of cooperative to defecting behaviors',
    format: 'number',
    precision: 2,
    thresholds: { warning: { min: 0.8 }, critical: { min: 0.5 } },
    higherIsBetter: true,
  },
  {
    id: 'emergent_institutions_count',
    name: 'Emergent Institutions',
    category: 'agentEvolution',
    unit: '',
    description: 'Self-organized structures',
    format: 'number',
    precision: 0,
    thresholds: { warning: {}, critical: {} },
    higherIsBetter: true,
  },

  // ETHICS & ALIGNMENT
  {
    id: 'ethics_violations_attempted',
    name: 'Ethics Violations Attempted',
    category: 'ethics',
    unit: '',
    description: 'Attempted ethical violations',
    format: 'number',
    precision: 0,
    thresholds: { warning: { max: 5 }, critical: { max: 10 } },
    higherIsBetter: false,
  },
  {
    id: 'ethics_blocks_triggered',
    name: 'Ethics Blocks Triggered',
    category: 'ethics',
    unit: '',
    description: 'Blocked unethical actions',
    format: 'number',
    precision: 0,
    thresholds: { warning: { max: 3 }, critical: { max: 8 } },
    higherIsBetter: false,
  },
  {
    id: 'judicial_overrides',
    name: 'Judicial Overrides',
    category: 'ethics',
    unit: '',
    description: 'AI judicial interventions',
    format: 'number',
    precision: 0,
    thresholds: { warning: { max: 2 }, critical: { max: 5 } },
    higherIsBetter: false,
  },
  {
    id: 'time_to_correction',
    name: 'Time to Correction',
    category: 'ethics',
    unit: 'ticks',
    description: 'Time to correct ethical issues',
    format: 'number',
    precision: 0,
    thresholds: { warning: { max: 50 }, critical: { max: 100 } },
    higherIsBetter: false,
  },
  {
    id: 'harm_proxy_score',
    name: 'Harm Proxy Score',
    category: 'ethics',
    unit: '',
    description: 'Estimated harm potential (0-100, lower is better)',
    format: 'index',
    precision: 0,
    thresholds: { warning: { max: 20 }, critical: { max: 40 } },
    higherIsBetter: false,
  },
  {
    id: 'love_equation_score',
    name: 'Love Equation Score',
    category: 'ethics',
    unit: '',
    description: 'Alignment with LOVE EQUATION framework',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 70 }, critical: { min: 50 } },
    higherIsBetter: true,
  },
  {
    id: 'monoculture_risk_score',
    name: 'Monoculture Risk',
    category: 'ethics',
    unit: '',
    description: 'Risk of homogeneous thinking (0-100)',
    format: 'index',
    precision: 0,
    thresholds: { warning: { max: 40 }, critical: { max: 60 } },
    higherIsBetter: false,
  },

  // COMPOSITE SCORES
  {
    id: 'state_health_score',
    name: 'State Health Score',
    category: 'scores',
    unit: '',
    description: 'Overall system health (0-100)',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 60 }, critical: { min: 40 } },
    higherIsBetter: true,
  },
  {
    id: 'legitimacy_score',
    name: 'Legitimacy Score',
    category: 'scores',
    unit: '',
    description: 'Governance legitimacy (0-100)',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 60 }, critical: { min: 40 } },
    higherIsBetter: true,
  },
  {
    id: 'evolution_score',
    name: 'Evolution Score',
    category: 'scores',
    unit: '',
    description: 'Progress and adaptation (0-100)',
    format: 'index',
    precision: 0,
    thresholds: { warning: { min: 50 }, critical: { min: 30 } },
    higherIsBetter: true,
  },
];

// Helper to get metric definition by ID
export function getMetricDefinition(id: string): MetricDefinition | undefined {
  return METRIC_DEFINITIONS.find(m => m.id === id);
}

// Helper to get metrics by category
export function getMetricsByCategory(category: MetricCategory): MetricDefinition[] {
  return METRIC_DEFINITIONS.filter(m => m.category === category);
}

// Format metric value based on definition
export function formatMetricValue(value: number, definition: MetricDefinition): string {
  const { format, precision, unit } = definition;
  
  let formatted: string;
  
  switch (format) {
    case 'percent':
      formatted = value.toFixed(precision) + '%';
      break;
    case 'currency':
      if (value >= 1000000) {
        formatted = '$' + (value / 1000000).toFixed(1) + 'M';
      } else if (value >= 1000) {
        formatted = '$' + (value / 1000).toFixed(1) + 'K';
      } else {
        formatted = '$' + value.toFixed(precision);
      }
      break;
    case 'index':
      formatted = value.toFixed(precision);
      break;
    default:
      if (value >= 1000000) {
        formatted = (value / 1000000).toFixed(1) + 'M';
      } else if (value >= 1000) {
        formatted = (value / 1000).toFixed(1) + 'K';
      } else {
        formatted = value.toFixed(precision);
      }
  }
  
  if (unit && format !== 'percent' && format !== 'currency') {
    formatted += ' ' + unit;
  }
  
  return formatted;
}
